let Name = game.askForString("what is your name")
let Color = game.askForString("what is you favorite color")
let DogorCat = game.askForString("do you like dogs or cats")
game.splash(" your name is: " + Name)
game.splash(" favorite color : " + Color)
game.splash(" you like: " + DogorCat)
game.reset()