let Name = game.askForString("what is your name")
let Color = game.askForString("what is you favorite color")
let DogorCat = game.askForString("do you like dogs or cats")
game.splash(" your name is: " + Name + " favorite color : " + Color + " you like: " + DogorCat)
game.reset()